# Testing file (you need VS Code with addon "REST Client")

###
POST https://ulf-kuehnle.de/wp/wp-content/plugins/ipn-adapter/endpoint.php
Content-Type: application/json

{
    "buyer_email": "test001@email.com",
    "address_email": "test001@email.com",
    "product_id": 12345,
    "event": "on_payment",
    "order_id": 4711,
    "address_last_name": "Mustermann",
    "address_first_name": "Max",
    "sha_sign": "87076F6FBBEE865420A7B7FDB57EDC3020D97F85632300F8D909BD7147F256D6DC87E30317B95A65C8677895D3163B2927D40874FC75BBDB7D08C81E88735392"
}

